baseurl = "https://gerov.es/"
title = "Sava Gerov"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Sava Gerov"
    info = "Dev"
    description = "Developer, proponent of agile development, XP and self-improvement. Iâ€™m enthusiastic about new technologies and Iâ€™m looking forward to pick up new skills."
    keywords = "blog,developer,sava,gerov"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "ğŸŒ Barcelona â€¢ Seville â€¢ Uppsala â€¢ Valencia â€¢ Sofia"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/sgerov"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/sgerov"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/savagerov/"

# Menu links
[[menu.main]]
    name = "ğŸ—’ writing"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "ğŸ¹ piano"
    weight = 3
    url = "/piano/"
